### PR TITLE
[Code Review] Brian Zitzow

### PR DESCRIPTION
**Pull request by bzitzow**
Bryce,

I'm assuming the application works, I'm sorry I didn't take the time to compile it and test it. 

Overall this is good. The code was easy to read and your variable names were expressive. Code is read much more than it is written, so that's a good thing!

You also provided error handling and feedback to the user, and handled input validation. Nice work!

The main feedback I have has to do with the application's structure. I wouldn't expect someone at your level to know this stuff, it comes from experience - but I didn't hold back. I've put the feedback in the comments as I figured that would be the easiest way to give it line by line. 

If you have any questions don't hesitate to ask.

Keep up the good work and happy coding!

P.S. Get a test framework setup and learn how to write some tests. It can be daunting at first, but the lessons learned will pay dividends in the long run AND separate you from other students when you enter the job market.

### CODE REVIEW

**Comment by bzitzow** [comment]
P.S. Configure your IDE to use spaces not tabs. :D

**Comment by bzitzow** [comment]
P.P.S. You get extra points for using Git. Nice work!

**Comment by brycemck** [comment]
Thank you, @bzitzow!! I'll look through these in a bit and make some edits;)

Really appreciate it!

**Comment by brycemck** [comment]
@bzitzow finished, let me know what you think ;)

**Pull request merged**
